name: Update remote repo

on:
    push:
        branches: [master]

jobs:
    remote_pull:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set ssh config
            run: |
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              chmod 400 ~/.ssh/id_rsa
              echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
              ssh infra@${{ secrets.SERVER_ADDR }} "cd /opt/remoteIO-esp8266 && git fetch && git pull origin master"
